### PR TITLE
Bugs in 3.0-dev

### PR DESCRIPTION
**Pull request by goetas**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | -
| Fixed issues | -

#### Summary
I've tested the master branch on a couple of real projects, this are ~5~ 3 independent bugs i've found, one for each commit

~All the commits include tests except of https://github.com/doctrine/migrations/pull/932/commits/66b13665515fc0eab636ea8a486b93b71d9e1e31. What happens if we want to do dry-run on an empty database? should the metadata table be created anyway?~

### CODE REVIEW

**Comment by SenseException** [comment]
Can you please describe the 5 Bugs this PR is covering? Why did you decide to handle 5 bugs with one PR?

**Comment by goetas** [comment]
- d235583 - ExecutionResult time is expressed in seconds (in some parts of the code the time was in seconds and sometimes in milliseconds, thus because of conversions, in the list of executed migrations, the displayed time was 1000 times longer)  
- b108ac9 - The first migration is always the migration "0" (as the description says, "first" should be the state when there are no migrations, previously was the first executed migration)
- fe628ad - Make target plan version argument mandatory (this is a minor change that allows to have less code duplication)
- fe628ad Do not display the project name twice via status command (in the migration status command, the project name is displayed twice, this could be not needed if https://github.com/doctrine/migrations/pull/933 gets merged)
 - 66b1366 - Initialize metadata when running migrations (this is controversial. What happens if we want to do dry-run on an empty database? should the metadata table be created anyway? will have to verify how 2.x behaves)

**Comment by goetas** [comment]
For an easier review and a quicker merge, I have removed the last commit. The metadata initialization will be fixed in a separate PR were will be easier to review the solution and check the tests.

**Comment by goetas** [comment]
Updated PR. only 3 bugs here now.

**Comment by greg0ire** [comment]
> d235583 - ExecutionResult time is expressed in seconds (in some parts of the code the time was > in seconds and sometimes in milliseconds, thus because of conversions, in the list of executed 
> migrations, the displayed time was 1000 times longer)
> b108ac9 - The first migration is always the migration "0" (as the description says, "first" should be > the state when there are no migrations, previously was the first executed migration)
> fe628ad - Make target plan version argument mandatory (this is a minor change that allows to 
> have less code duplication)

Please include these explanations in the commit messages.

> ExecutionResult time is expressed in seconds

Is that the buggy behavior you want to fix, or is that the correct behavior you enforced

> The first migration is always the migration "0"

Same question, here, I think it's the correct one, but I'd like to be sure.

Tip: complete the sentence `If applied, this commit will` to make your commit message subject, it will avoid that kind of confusion.

**Comment by goetas** [comment]
@greg0ire thanks for the review. I have pushed the updated commit messages

**Comment by greg0ire** [comment]
Thanks @goetas !

**Pull request merged**
