### PR TITLE
Remove unused AbstractMigration::$configuration and fix some CS

### PR DESCRIPTION
**Pull request by rybakit**

### CODE REVIEW

**Comment by rybakit** [comment]
Any comment on why this was closed?

**Comment by mikeSimonson** [comment]
@rybakit You are making too many different changes in your commit. It's very hard to read.
You are removing the Version use for instance too which apparently shouldn't.

**Comment by rybakit** [comment]
@mikeSimonson `use Doctrine\DBAL\Migrations\Version` is superfluous there, as both classes (`AbstractMigration` and `Version`) share the same namespace.

**Comment by stof** [comment]
Reopening as this CS changes are indeed right.

@rybakit can you rebase your branch to fix conflicts ?

**Comment by rybakit** [comment]
@stof, @mikeSimonson Rebased.

**Comment by mikeSimonson** [comment]
@rybakit Thanks

**Pull request merged**
