### PR TITLE
Use executeUpdate instead of executeQuery for write operation

### PR DESCRIPTION
**Pull request by goetas**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | -

#### Summary

Use executeUpdate for migration queries as it is a write operation

### CODE REVIEW

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

**Comment by greg0ire** [comment]
Also, since there is no BC-break, this should probably target 2.2.x , can another contributor confirm this?

**Comment by alcaeus** [comment]
@greg0ire that is correct - this could easily go into 2.3.0. @goetas do you see any reason why this shouldn't be in 2.3?

**Comment by goetas** [comment]
I think that this could perfectly go into 2.x too.

**Comment by alcaeus** [comment]
Sounds good - can you rebase this onto 2.3.x please? Thanks!

**Comment by greg0ire** [comment]
Oooh it's a duplicate in fact, closing see #888

**Pull request closed without merging**
