### PR TITLE
Reversed the conditional in isACustomPharBuild()

### LINKED ISSUE #229: MigrationsVersion::VERSION returns @git-version@
I may have misunderstood this but when installing doctrine/migrations as a standalone tool, @git-version@ is being returned as the version string rather than the static $version property (currently v1.0.0-alpha3).

### PR DESCRIPTION
**Pull request by liquorvicar**
Fixes #229

### CODE REVIEW

**Comment by mikeSimonson** [comment]
Thanks @liquorvicar

**Comment by stof** [comment]
The fix is wrong. the function name now does the opposite of what the name describes. Either the *usage* of the function should have changed, or the function should also be renamed

**Comment by mikeSimonson** [comment]
This is so confusing.

If '@git-version@' is passed to the function, it is not a custom phar build and thus the function should return false.
If something else is passed to the function that means that the '@git-version@' string has been replaced by box and thus that it is a custom phar build (return true).

Isn't that what is going on here ?

**Comment by stof** [comment]
ah sorry, indeed

**Pull request merged**
