### PR TITLE
Support for non-transactional migrations.

### PR DESCRIPTION
**Pull request by klandaika**
Some DB engines do not support ALTER statements inside a transaction. Added ability to disable transaction on individual migration level by overriding  the isTransactional() function.

EDIT 12/6/2014 (in reply to rjmunro):
One database which experiences this issue that I ran across is Pervasive SQL: http://www.pervasive.com/database

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@klandaika Do you still count to make those change in your PR ?

**Comment by klandaika** [comment]
@mikeSimonson Yes, just committed the changes.

**Comment by mikeSimonson** [comment]
@klandaika Thanks

**Comment by mikeSimonson** [comment]
It's merged.
Thanks

**Pull request closed without merging**
