### PR TITLE
Handle missing jdorn/sql-formatter dependency in dump-schema command

### PR DESCRIPTION
**Pull request by webimpress**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

We are doing it in diff command, but not in dump-schema and because of that we are getting exception with trace on console output:

```console
$ vendor/bin/doctrine-migrations dump-schema --formatted

Fatal error: Uncaught Error: Class 'SqlFormatter' not found in /usr/src/vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/SqlGenerator.php:56
Stack trace:
#0 /usr/src/vendor/doctrine/migrations/lib/Doctrine/Migrations/SchemaDumper.php(66): Doctrine\Migrations\Generator\SqlGenerator->generate(Array, true, 120)
#1 /usr/src/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php(79): Doctrine\Migrations\SchemaDumper->dump('20190726073612', true, 120)
#2 /usr/src/vendor/symfony/console/Command/Command.php(255): Doctrine\Migrations\Tools\Console\Command\DumpSchemaCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/src/vendor/symfony/console/Application.php(921): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/src/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Appl in /usr/src/vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/SqlGenerator.php on line 56
```

Command `diff` handles it much better:
```
$ vendor/bin/doctrine-migrations diff --formatted


In InvalidOptionUsage.php line 13:
                                                                                                                                   
  The "--formatted" option can only be used if the sql formatter is installed. Please run "composer require jdorn/sql-formatter". 
```

so the user knows what to do.

### CODE REVIEW

**Comment by webimpress** [comment]
@SenseException I would love to but there is no one also for diff command... and I do not have time to work on it now... Sorry.

**Comment by alcaeus** [comment]
> Can you please add a new test for that case?

That's also not possible since we require the formatter in our dev dependencies, so we won't trigger that case anyways.

**Comment by alcaeus** [comment]
Thanks @webimpress!

**Comment by webimpress** [comment]
@alcaeus 
> That's also not possible since we require the formatter in our dev dependencies

Oh... actually _it is_ possible. This is how we did it in zend framework:
https://github.com/zendframework/zend-expressive/blob/master/test/Container/ResponseFactoryFactoryWithoutDiactorosTest.php

**Comment by alcaeus** [comment]
Yeah, that could work. Feel like adding it? 😛

**Pull request merged**
