### PR TITLE
Merge release 2.2.1 into 2.3.x

### PR DESCRIPTION
**Pull request by doctrinebot**
Release [2.2.1](https://github.com/doctrine/migrations/milestone/29)

2.2.1
=====

- Total issues resolved: **0**
- Total pull requests resolved: **2**
- Total contributors: **2**

Bug
---

 - [887: &#91;2.2.x&#93; Allow to throw Exception in Migrations](https://github.com/doctrine/migrations/pull/887) thanks to @VincentLanglet

Documentation
-------------

 - [870: Fixed typo in the &quot;--no-interaction&quot; argument](https://github.com/doctrine/migrations/pull/870) thanks to @mattchete

### CODE REVIEW

**Comment by alcaeus** [comment]
@goetas I'll let you decide whether to merge this manually when you upmerge to master, but you can also merge this PR and go from there.

**Comment by goetas** [comment]
Will merge manually, to have a fast forward commit. Are you ok with it?

**Comment by alcaeus** [comment]
Sounds good to me.

**Comment by greg0ire** [comment]
What do you mean by fast forward commit? The only situation if you could have a fast forward would be if 2.2 were based on 2.3, is that the case?

**Comment by goetas** [comment]
My bad, I think I have misunderstood the feature

**Comment by goetas** [comment]
Will take care of it tomorrow

**Comment by greg0ire** [comment]
I can take care of it if you want. IMO we just have to merge this or overwrite 2.3.x with this 2.2.x-merge-up-into-2.3.x_5e182ad4f31eb2.86467913 if we want to avoid the double merge commit

**Pull request merged**
