### PR TITLE
Replacing the deprecated class DialogHelper to QuestionHelper.

### LINKED ISSUE #361: migrations:status --show-version shows all executed migrations under "executed unavailable"
**Run:**
   doctrine:migrations:status --show-version

**Result:**
"Available Migration Versions" and "Previously Executed Unavailable Migration Versions" lists contain same migration numbers. Available migration versions are shown under both lists.

**Expected result:**
"Previously Executed Unavailable Migration Versions" should contain only migrations that are executed but no longer available.

**Fix:** https://github.com/doctrine/migrations/pull/360

### PR DESCRIPTION
**Pull request by nastron**
This fixes #361.

### CODE REVIEW

**Comment by kusmierz** [comment]
Any chances to merge it?

**Comment by mikeSimonson** [comment]
@kusmierz As soon as the 1.0 is out wich is soon too.

**Comment by stof** [comment]
-1 for the current approach. We should not drop support for the Symfony 2.3 LTS while supporting both the old API and the new API in parallel is not hard.

**Comment by mikeSimonson** [comment]
@stof Can you link to an example ?

**Comment by bizmate** [comment]
Is this in anyway linked to a connection error? I could not figure out why the db connection is failing despite correct configuration being passed
http://pastie.org/10182707

**Comment by mikeSimonson** [comment]
@bizmate No, can you open another issue

**Pull request closed without merging**
