### PR TITLE
No finder sort

### PR DESCRIPTION
**Pull request by goetas**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | https://github.com/doctrine/migrations/issues/1172

### CODE REVIEW

**Comment by goetas** [comment]
The phpunit failure is weird...

**Comment by greg0ire** [comment]
It's not that weird, see https://github.com/doctrine/migrations/pull/1175 :slightly_smiling_face:

**Comment by greg0ire** [comment]
I think it needed a rebase to pass on AppVeyor too, hence my force push :raised_back_of_hand:

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @goetas !

**Comment by goetas** [comment]
this change relates to https://github.com/doctrine/migrations/pull/858/commits/5c3ceed3001c431d1df5bd3f1e18efe8ead4b3b0

**Pull request merged**
