### PR TITLE
Resolves #939 replaced single quotes with nowdoc

### LINKED ISSUE #939: Nowdoc strings
### Feature Request

Generate multiline SQL (from `--formatted`) statements using nowdoc strings instead of current single quoted strings.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

The main advantage of nowdoc strings is that you don't need to escape characters inside, so a raw query can be put inside. It makes sense for multiline queries (like create table, for example), because escaping breaks SQL highlighting in IDE (PHPStorm, for example, highlights SQL strings, but if there are escaped quotes (`'... COMMENT \'(DC2Type:carbondatetime)\' ...'`), the whole highlighting breaks and reports it as a syntax error).

Not a big deal, but IMO nice to have.

### PR DESCRIPTION
**Pull request by averatec1337**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #939

### CODE REVIEW

**Comment by greg0ire** [comment]
Thanks for working on this. It seems there are CI jobs failing. Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to handle those.

**Comment by averatec1337** [comment]
@greg0ire thanks, I had to fix units.

**Comment by greg0ire** [comment]
You need to fix cs as well, and you might want to retarget on `origin/3.9.x`

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @kamil-karkus !!!

**Comment by averatec1337** [comment]
@greg0ire Thank you for taking care of this issue. I was planning to get back to it on Monday, following the guide you sent.

**Comment by vinise** [comment]
Really sad not to see any option on this feature.
could have been great to be able to disable it, or an option to activate this either on formatted sql only or based on --line-length=LINE-LENGTH (or other option)
(I might create a PR for this if I find some time)
 
 ;)

**Pull request merged**
