### PR TITLE
CI: Test against PHP 7.3

### PR DESCRIPTION
**Pull request by Majkl578**
|      Q       |   A
|------------- | -----------
| Type         | improvement

### CODE REVIEW

**Comment by Majkl578** [comment]
This is blocked by ORM issue that will be fixed in ORM 2.6.3.

**Comment by Majkl578** [comment]
This is ok now.

**Comment by alcaeus** [comment]
@Majkl578 needs a rebase to be mergeable.

**Comment by Majkl578** [comment]
This is safe to merge without rebase, otherwise I'll rebase it later.

**Comment by alcaeus** [comment]
Somebody configured branch protection that way, I just do what it says...

image

**Pull request merged**
