### PR TITLE
use yoda comparison

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by lcobucci** [comment]
@OskarStark thanks, but we're discussion about REMOVING yoda expressions everywhere: https://github.com/doctrine/coding-standard/pull/9/commits/e36b36739176b7e25a9b76b2979d982421111cfe#diff-1d794c8c2cf3bf4d562ddaea8be99bb0R131

**Comment by OskarStark** [comment]
Why? 👀

**Comment by Majkl578** [comment]
You can find some reasoning and other rules in the https://github.com/doctrine/coding-standard/pull/9 - it's still just a proposal for comments, not accepted CS.
@greg0ire wrote an article about uselessness of Yoda conditions: [Why using Yoda conditions you should probably not be ](https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not)

**Comment by greg0ire** [comment]
Couldn't agree more of course, but some people like whoever that "@Ocramius" guy is do not: https://www.reddit.com/r/PHP/comments/6rl40r/comment/dl6topg
Probably just some random n00b though :P

**Comment by OskarStark** [comment]
Feel free to reopen if you need it :)

**Pull request closed without merging**
