### PR TITLE
build: Update Box

### PR DESCRIPTION
**Pull request by theofidry**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

Update to the latest Box version.

Depends on #1332

### CODE REVIEW

**Comment by theofidry** [comment]
@greg0ire this probably requires a manual approval in order to trigger the CI

**Comment by greg0ire** [comment]
I'm AFK but I think I might have wrongly configured the `paths` option in the github workflow.

**Comment by greg0ire** [comment]
See https://github.com/doctrine/migrations/pull/1290. Please add the sh file where relevant 🙏

**Comment by theofidry** [comment]
@greg0ire you would need to merge it to 3.6.x, or should this target 3.5.x? (in which case so should the previous ones that were merged)

**Comment by greg0ire** [comment]
3.5 is unmaintained. Looking at the work flow, paths is present, so I think my PR was merged up. I'll be AFK until Thursday, but feel free to open a merge up PR if you think stuff present in 3.5 is missing in 3.6

**Comment by greg0ire** [comment]
@theofidry I'm back from hols, I pushed a new commit so that the relevant jobs are triggered :slightly_smiling_face:

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
@theofidry if this looks OK to you, please, mark it as ready for review and I'll merge :)

**Comment by theofidry** [comment]
I see the download of box but no building or test of the built PHAR, is that expected?

**Comment by greg0ire** [comment]
As soon as the phar is available, the building and test do happen, but as a PHPUnit test, not as a separate github action: https://github.com/doctrine/migrations/blob/3.6.x/tests/Doctrine/Migrations/Tests/BoxPharCompileTest.php#L18-L70

**Comment by greg0ire** [comment]
Thanks @theofidry !

**Comment by theofidry** [comment]
Should probably be updated to 4.4.0 now :)

**Comment by greg0ire** [comment]
Working on it: https://github.com/doctrine/migrations/pull/1365

**Pull request merged**
