### PR TITLE
Drop php 7.1 and allow phpunit 8

### PR DESCRIPTION
**Pull request by goetas**
|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | -

### CODE REVIEW

**Comment by lcobucci** [comment]
Let's just bump up php version and require phpunit 8. Much easier for everyone 😁

**Comment by goetas** [comment]
phpunit 8 requires php 7.2, while the minimum version for doctrine migrations is 7.1. Is it ok to increase the min version to 7.2 for this library too?

**Comment by greg0ire** [comment]
>  Is it ok to increase the min version to 7.2 for this library too?

7.1 is EOL, I think it is ok.

**Comment by goetas** [comment]
>> Is it ok to increase the min version to 7.2 for this library too?

> 7.1 is EOL, I think it is ok.

Happy to hear that. Build is green!

**Comment by greg0ire** [comment]
FWIW, I think we could even do this on 2.2.x , not sure what others think.

**Comment by goetas** [comment]
appveyor is having some issues https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/

**Comment by alcaeus** [comment]
@greg0ire I don’t see a reason to drop 7.1 in 2.x.

**Comment by greg0ire** [comment]
Allowing new features like the `object` type declaration in new code could be a reason, but maybe that's something we want to do if and when someone makes a PR that would benefit from such features.

**Comment by alcaeus** [comment]
We can always do that when the new API shows up.

**Pull request merged**
