### PR TITLE
Disallow down migration if it was never migrated up

### PR DESCRIPTION
**Pull request by cb0**
|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | #874

#### Summary
Before running a down migration script, the migration repository will be checked to see if it was ever executed. 
It the migration did not run, a Exception of type VersionDoesNotExist will be thrown.

### CODE REVIEW

**Comment by goetas** [comment]
The whole propose of `execute`, is to run a migration independently if it was migrated or not.
I think that this PR should be closed.

**Review by goetas — CHANGES_REQUESTED** [review]
The whole propose of execute, is to run a migration independently if it was migrated or not.
I think that this PR should be closed.

**Comment by cb0** [comment]
@goetas Thanks for your review. 
I'm just beginning and might not see the whole picture.

But from my point of view, it is dangerous to "to run a migration independently if it was migrated or not". It should only be able to migrate down, if it was migrated up. Otherwise the database "could" result in an inconsistent state, depending on the content of the migration.

Or do I missunderstand something here ?

**Comment by goetas** [comment]
You are perfectly right. it is dangerous, but this is the whole propose of this command, being able to run arbitrary migrations. Sometimes is useful sometimes is dangerous. 

What about changing the behavior of this command to not execute up/down the migration if it has not been executed in the opposite direction? and adding an `--force` option to override the check.

In this way we get a safe execute by default (the behavior you wanted), but it allows to override it when necessary.

**Comment by goetas** [comment]
@cb0 let me know if you are interested to continue to work on this. Implementing it as suggested in https://github.com/doctrine/migrations/pull/900#issuecomment-573570567 will be possible only before tagging 3.0.

**Pull request closed without merging**
