### PR TITLE
Confinguration: check if migration class exists added

### PR DESCRIPTION
**Pull request by TomasVotruba**
This should prevent issue that happened to me and to users of package I maintain.

Migration class may not found due to typo in it's namespace, name or the namespace set in configuration.

This should tell user before it fail [while trying to create non-existing class in Version](https://github.com/doctrine/migrations/blob/68cc7bf629a7c1fc0696e583cc8ed46f897d0afb/lib/Doctrine/DBAL/Migrations/Version.php#L116). Took me while to figure out, what it really meant and where the failure was (naming namespace `Migrations` vs `migrations` etc.).

Test provided.

What do you think?

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@TomasVotruba I like it.
Can you move your exception has a method into the migrationException class.
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/MigrationException.php

**Comment by TomasVotruba** [comment]
Thanks for feedback.

Do you mean something like `MigrationException::classNotFound()`?

**Comment by mikeSimonson** [comment]
More something like MigrationException::migrationClassNotFound()

**Comment by TomasVotruba** [comment]
@mikeSimonson Done.

**Comment by mikeSimonson** [comment]
@TomasVotruba Thanks

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
