### PR TITLE
Add attributes to commands

### PR DESCRIPTION
**Pull request by gordinskiy**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #1329 

Add usage of `Symfony\Component\Console\Attribute\AsCommand` attributes

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you. Can you please also add the `description:` parameter to all attributes?

**Review by derrabus — APPROVED** [review]

**Comment by pkruithof** [comment]
@derrabus any progress on this?

**Comment by greg0ire** [comment]
The backward compat check can be ignored, but the static analysis check should get fixed before this can be merged.

**Comment by gordinskiy** [comment]
> Ignored error pattern ^Call to function method_exists\(\) with Doctrine\\Migrations\\Metadata\\Storage\\MetadataStorage and 'getSql' will always evaluate to true\.$ in path /home/runner/work/migrations/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php was not matched in reported errors.

How to fix this error correctly?
Remove the check, and move the method from the annotation to the interface itself?

**Comment by greg0ire** [comment]
Rebasing might be enough: it does not seem to come from your changes. I'll try closing and reopening in case that does the trick.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @gordinskiy !

**Pull request merged**
