### PR TITLE
Simplify handling of `--all-or-nothing` and `--no-all-or-nothing` options

### PR DESCRIPTION
**Pull request by agustingomes**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | 
#### Summary

Allowing passing values to options for `--all-or-nothing` option is now removed, which allows the configuration of the negatable option `--no-all-or-nothing`, whihc in its turn allows to remove the added option in 3.8.1.

The outcome is a much simpler logic to override the configuration of `all_or_nothing` via the CLI command.

### CODE REVIEW

**Comment by greg0ire** [comment]
Merge up done, please address the conflicts

**Comment by agustingomes** [comment]
@greg0ire I'll be away for the weekend, but I'll push the rebase around Monday.

**Comment by agustingomes** [comment]
@greg0ire rebased onto `4.0.x` and only the backward compatibility check is failing. How do we proceed with that failure?

**Comment by greg0ire** [comment]
We ignore it, since breaking changes (here, removing a class) are OK during a major upgrade.

**Review by greg0ire — DISMISSED** [review]

**Review by greg0ire — COMMENTED** [review]
Please document the breaking changes in `UPGRADE.md`

**Comment by agustingomes** [comment]
@greg0ire I pushed a new entry in the `UPGRADE.md`. Let me know if the phrasing needs extra work.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @agustingomes !

**Pull request merged**
