### PR TITLE
Exclude phpstan file with .gitattributes

### PR DESCRIPTION
**Pull request by VincentLanglet**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

Same idea @greg0ire 

There is also possibly
- download-box.sh
- build-phar.sh

but I don't know what there are doing

### CODE REVIEW

**Comment by greg0ire** [comment]
They are used when running tests or running the phar, I think it is safe to remove them as well.

**Comment by VincentLanglet** [comment]
> They are used when running tests or running the phar, I think it is safe to remove them as well.

I added them

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks!

**Comment by VincentLanglet** [comment]
> They are used when running tests or running the phar, I think it is safe to remove them as well.

I just saw the `.doctrine-project.json` were downloaded too on every project
https://github.com/doctrine/migrations/blob/3.6.x/.doctrine-project.json

Do you know the purpose of this file ? Can we add it too to the gitattributes ?

**Pull request merged**
