### PR TITLE
Allow PHP 8 in 2.x

### LINKED ISSUE #1048: Support for PHP8 in 2.x
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

Allow PHP8

### PR DESCRIPTION
**Pull request by greg0ire**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | n/a

#### Summary

We want to let downstream project experiment while we fix our issues if we have some. Failures are allowed for now, and should no longer be once feature freeze starts.

### CODE REVIEW

**Comment by greg0ire** [comment]
There is currently no version of `doctrine/migrations` that supports DBAL 3, so maybe let's wait until we do have one and merge this in that branch instead of committing to supporting php 8 on 2.2.x. cc @alcaeus

**Comment by goetas** [comment]
does dbal 2 allow php?

**Comment by greg0ire** [comment]
All versions of DBAL require php :trollface: 
but if you mean php 8, then no, it's only DBAL 3.

**Comment by peterrehm** [comment]
@greg0ire As dbal 2 is compatible with PHP8, is there anything blocking a version of migrations and migrations-bundle for php8?

**Comment by greg0ire** [comment]
In theory no, good point! In practice, the build is currently broken, so I will get on to it when #1069 is resolved.

**Comment by greg0ire** [comment]
@peterrehm actually, we depend on `ocramius/proxy-manager`, which does not seem to have a version compatible with PHP 8 :grimacing:

**Comment by greg0ire** [comment]
That hurdle is passed now, the next one is https://github.com/doctrine/orm/pull/8303

**Comment by nicwortel** [comment]
@greg0ire hi! I'm happy to see that work is already in progress to have doctrine/migrations support PHP 8.0.

doctrine/orm#8303 is merged now. Am I correct in assuming that a new version of doctrine/orm has to be released before doctrine/migrations can support PHP 8.0? Is there anything I can do to help? Thanks!

**Comment by greg0ire** [comment]
Hi @nicwortel! You are correct.

> Is there anything I can do to help?

As a matter of fact yes!

In [this list](https://github.com/orgs/doctrine/projects/7#card-50248429) there are some packages that still use Travis CI. We are going to migrate them to Github Actions, which is a big undertaking, but in the meantime, if you want to add a build job for image `8.0snapshot` that does not allow failure, that would be great! It's as easy as adding one item to this list: https://github.com/doctrine/event-manager/blob/348f72ec92c7e0b1f5462f6616af2b448ba3cbb1/.travis.yml#L13

If you do want to help with this, please try on one package first, get a review, and then if it gets merged, proceed with the other PRs.

**Comment by nicwortel** [comment]
> In [this list](https://github.com/orgs/doctrine/projects/7#card-50248429) there are some packages that still use Travis CI. We are going to migrate them to Github Actions, which is a big undertaking, but in the meantime, if you want to add a build job for image `8.0snapshot` that does not allow failure, that would be great! It's as easy as adding one item to this list: https://github.com/doctrine/event-manager/blob/348f72ec92c7e0b1f5462f6616af2b448ba3cbb1/.travis.yml#L13
> 
> If you do want to help with this, please try on one package first, get a review, and then if it gets merged, proceed with the other PRs.

Sure! So if I understand you correctly, you're asking me to add `8.0snapshot` (since `8.0` isn't available yet) jobs to the Travis CI builds of the repositories listed in the "Allow PHP8 and test packages with it" card that don't have a checked checkbox yet, correct? So currently that would be event-manager, data-fixtures, lexer, migrations, DoctrineMigrationsBundle and DoctrineMongoDBBundle.

afbeelding

Would you like me to try to immediately migrate from Travis CI to GitHub Actions in the same PRs (assuming it's doable and the PRs don't become too big) or would you prefer that to happen in separate PRs?

**Comment by greg0ire** [comment]
You understood correctly what I was asking :slightly_smiling_face: 
I'm not even sure the builds currently pass because of Composer 2, so try small at first please, you might be surprised to see how it grows into "upgrade the coding standard library", and so on and so on.

**Comment by fpesch** [comment]
any eta on this?

**Comment by greg0ire** [comment]
@bpesch yes: it's the ETA of all the blockers + 1 day I suppose.

**Comment by maxhelias** [comment]
It seems that only https://github.com/Ocramius/ProxyManager/pull/628 left which blocks. If you need help, maybe I can try something ?

**Comment by greg0ire** [comment]
@maxhelias thanks but as you pointed out, we are blocked, and we don't need help being blocked, we can do that ourselves :smile:

**Comment by Volga** [comment]
> @maxhelias thanks but as you pointed out, we are blocked, and we don't need help being blocked, we can do that ourselves

How about removing the dependency on Ocramius/ProxyManager? Its owner said that his priority now is a game console.
https://github.com/Ocramius/ProxyManager/pull/628#issuecomment-742464460

**Comment by ghost** [comment]
This merge request is cancel ?

**Comment by SenseException** [comment]
Blocked is not cancelled.

**Comment by alcaeus** [comment]
As was done in #1101, we can use the FriendsOfPHP/proxy-manager-lts package to unblock running on PHP 8. This allows generating proxies on PHP 8, **as long as they only use 7.4 language features**. Using PHP 8 features (e.g. union return types) will be possible once this is supported in the upstream package. I suggest using the LTS fork in 2.x as well.

**Comment by alcaeus** [comment]
Replaced by #1102.

**Pull request closed without merging**
