### PR TITLE
Run tests on PHP 8.1 as well

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by greg0ire** [comment]
Should we do something similar for appveyor?

**Comment by derrabus** [comment]
We can bump AppVeyor to PHP 8.1 as well, if you want. But I wouldn't create a another build matrix for different PHP versions there. That's probably a waste of resources.

**Comment by greg0ire** [comment]
Ok then let's bump it, the latest PHP should be more efficient, right? 👍

**Comment by derrabus** [comment]
Done.

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
