### PR TITLE
Update license to MIT.

### LINKED ISSUE #623: Change license to MIT
In order to change the license on this project, we have to get the approval of every past contributor. At the time of writing this we have had 107 contributors.

If you are reading this and you are a contributor on the below list, please reply to this GitHub issue with the following text:

```
I, @username, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.
```

- [x] @PapsOu
- [x] @DavidHavl 
- [x] @jkrcma 
- [x] @ErikSaunier 
- [x] @tavy315
- [x] @meckhardt
- [x] @shawndellysse
- [x] @rjmunro
- [x] @craigmarvelley
- [x] @mikeSimonson 
- [x] @dt-creasis
- [x] @pezia
- [x] @AolEvanFribourg
- [x] @Ocramius
- [x] @radekhubner 
- [x] @simensen 
- [x] @hype-
- [x] @robinvdvleuten
- [x] @alOneh
- [x] @jrobeson
- [x] @korstiaan
- [x] @sheridan-dev
- [x] @Padam87
- [x] @antonbabenko 
- [x] @m00t
- [x] @craue
- [x] @c960657
- [x] @aderuwe
- [x] @arnaud-lb 
- [x] @aaa2000
- [x] @tombevers
- [x] @maxim-oleinik
- [x] @gsomoza
- [x] @ReenExe
- [x] @iVariable
- [x] @ErikTrapman
- [x] @vershnik 
- [x] @aivus
- [x] @syzygymsu
- [x] @jwage
- [x] @Majkl578
- [x] @fabpot
- [x] @rybakit
- [x] @beberlei
- [x] @localheinz
- [x] @TomasVotruba
- [x] @rcatlin
- [x] @neeckeloo
- [x] @alcaeus 
- [x] @ornicar
- [x] @Nyholm
- [x] @asgrim
- [x] @stof
- [x] @lsmith77
- [x] @lcobucci
- [x] @mantiz
- [x] @shieldo
- [x] @Jean85
- [x] @Safranil 
- [x] @egircys
- [x] @kriswallsmith
- [x] @drefixs
- [x] @farzadghanei
- [x] @diewom
- [x] @greg0ire
- [x] @carusogabriel 
- [x] @mpdude
- [x] @kkamkou
- [x] @jalliot
- [x] @tifabien
- [x] @bamarni
- [x] @thanosp
- [x] @cassiosantos
- [x] @pborreli
- [x] @mlocati
- [x] @bountin
- [x] @itised
- [x] @chrisguitarguy 
- [x] @weaverryan
- [x] @schmittjoh
- [x] @burci
- [x] @liquorvicar
- [x] @xosofox
- [x] @smatyas
- [x] @tvlooy
- [x] @Aliance 
- [x] @r0b1n
- [x] @kander
- [x] @Seldaek
- [x] @jeromegamez
- [x] @BreiteSeite
- [x] @funivan
- [x] @eko
- [x] @schroedan
- [x] @rodnaph
- [x] @kimhemsoe
- [x] @denderello
- [x] @michaelperrin
- [x] @mrtorrent
- [x] @sergiughf
- [x] @abacaphiliac
- [x] @tobiasstadler
- [x] @guilhermeblanco
- [x] @Soullivaneuh

Don't need approval from these people?

- [ ] @bizmate - changes are trivial and have been mostly committed over ([commits](https://github.com/doctrine/migrations/commits?author=bizmate))
- [ ] @louiscytc - changes trivial enough to not require approval? ([commits](https://github.com/doctrine/migrations/commits?author=louiscytc))

### PR DESCRIPTION
**Pull request by jwage**
Fixes #623

### CODE REVIEW

**Comment by stof** [comment]
We still need a few approvals, right ?

**Comment by jwage** [comment]
Yes, just preparing the PR ahead of time.

**Comment by stof** [comment]
should we merge this in 1.x as well, so that both maintained branch are under the same license ? this would simplify the maintenance, as we would not need to accept LGPL contributions to 1.X and then asking contributors to accept moving them to MIT when applying the same fix in 2.0.

**Comment by jwage** [comment]
Yes

**Pull request merged**
