### PR TITLE
Let composer decide the best version

### PR DESCRIPTION
**Pull request by PowerKiKi**
|      Q       |   A
|------------- | -----------
| Type         | dcos
| BC Break     | no
| Fixed issues | none

#### Summary

Let composer decide the best version, instead of hardcoding somehting in the docs.

### CODE REVIEW

**Comment by greg0ire** [comment]
This should probably target a lower branch.

**Comment by goetas** [comment]
@PowerKiKi  can you target `2.3.x` with your change?

**Comment by PowerKiKi** [comment]
done

**Comment by goetas** [comment]
thank you!

**Pull request merged**
