### PR TITLE
Dry run added to pre and post methods

### PR DESCRIPTION
**Pull request by MikeTralala**
When adding a column, we can't use `$this->addSql()` in postUp because this is not executed anymore. So we use `$this->connection->executeSql()`. This works fine if you execute the migration directly the database. But if you are dry-running to check if all is well, i dont want my postUp to execute any statements.

### CODE REVIEW

**Comment by stof** [comment]
this is impossible, because it is a BC break (child classes must respect the signature

**Comment by MikeTralala** [comment]
Is there any other kind of setup that would do the trick?

**Comment by chrisguitarguy** [comment]
You could add a property to `AbstractMigration` along with a `isDryRun` method and a setter for the property. Then set the dry run value in `Version` and let folks check `$this->isDryRun()` in their migration methods.

**Comment by mikeSimonson** [comment]
The obvious solution here is to split your migration in 2 different migrations.

There is no other way that I can think off that wouldn't cause a massive BC break.

**Comment by mikeSimonson** [comment]
@MikeTralala Also don't forget to put your .idea folder in your global gitignore to avoid committing it by accident.

**Comment by dbu** [comment]
funny, we just stumbled over the same problem. i think this is something that should be re-thought for version 2. maybe postUp does not need to be executed at all in dry run mode? preUp might need it though, and it will be particularly relevant to know whether we are in dry run mode.

in our postUp, we use this workaround to check if the actual migration was executed or not:

```php
if (!in_array($newTableName, $schema->getTableNames())) {
    echo 'skip post update, this is a dry run';
    // this was a dry-run
    return;
}
```

**Comment by MikeTralala** [comment]
@dbu Thanks haven't thought of that fix... and @mikeSimonson Sorry i forgot, thanks for the reminder.

**Pull request closed without merging**
