### PR TITLE
Drop application name as it has no real use case

### PR DESCRIPTION
**Pull request by goetas**
|      Q       |   A
|------------- | -----------
| Type         | rfc
| BC Break     | -
| Fixed issues | -

#### Summary

currently the "application name" has no real propose and people (as I know...) always is set to some default. i suggest to simply remove it

### CODE REVIEW

**Comment by goetas** [comment]
@alcaeus @greg0ire @SenseException  what do you think about this?

**Comment by SenseException** [comment]
Judging by the diff it doesn't seem to have an impact on migrations when the application name is removed. Are there any changes needed for the documentation if this PR would get an okay?

**Comment by alcaeus** [comment]
> what do you think about this?

No point keeping it around just to output it when a command is run. I'm ok with dropping it as long as we deprecate it first ;)

**Comment by goetas** [comment]
Can someone approve it? (@alcaeus  the forward compatibility chapter is still open for 2.x and would like to handle it once all the changes in 3.x are merged)

**Comment by greg0ire** [comment]
What do you mean by "chapter"?

**Comment by goetas** [comment]
I mean that 3.x introduced BC breaks, and none of them have the deprecation layer in place for now inside the 2.x branch

**Comment by goetas** [comment]
Will do my best with that. I think that not too many people have used doctrine/migrations as a library, but just as dependency

**Pull request merged**
