### PR TITLE
travis: drop PHP 7.0 from allowed failures, it passes well

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@TomasVotruba I prefer to wait for the final release to do that.

**Comment by TomasVotruba** [comment]
Sure, it's in matter of weeks. Feel free to merge after the release.

**Comment by mikeSimonson** [comment]
@TomasVotruba Thanks

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
