### PR TITLE
composer: use PSR-4 autoload

### PR DESCRIPTION
**Pull request by TomasVotruba**
PSR-0 is deprecated

### CODE REVIEW

**Comment by localheinz** [comment]
:+1:

**Comment by mikeSimonson** [comment]
@stof ?

**Comment by stof** [comment]
Well, this works, but it is not consistent with the decision done for the ORM and DBAL.

**Comment by TomasVotruba** [comment]
@stof Could you link me there?

**Comment by TomasVotruba** [comment]
@stof It's already merged for ORM: https://github.com/doctrine/doctrine2/commit/726383cafb546cfdb5bd5f9175594cd137c0a415

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
