### PR TITLE
Fixed --write-sql input option default value

### PR DESCRIPTION
**Pull request by podorozhny**

### CODE REVIEW

**Comment by stof** [comment]
This looks wrong to me:

- `getOption()` will now be `true` even when the option is not passed explicitly (as I said, using optional values in options is tricky, as it would actually require 2 different defaults)
- `true` is not a path

**Comment by podorozhny** [comment]
What about something like that?

**Comment by stof** [comment]
have you tried it for real for the different cases ?

**Comment by podorozhny** [comment]
> have you tried it for real for the different cases ?

Yep, `migrations:migrate -n`, `migrations:migrate --write-sql`, `migrations:migrate --write-sql=test.sql` works as expected (first one executes migrations and the rest - writes it to current working dir).

**Comment by jwage** [comment]
This will be fixed in 2.0 via #666

**Comment by podorozhny** [comment]
iwkad22

**Comment by jwage** [comment]
@podorozhny is there a problem?

**Comment by jwage** [comment]
@podorozhny I am assume the passive aggressive picture is because you want to see a fix in 1.x? or you wanted this PR to be merged? Let me know. I am open to merging a fix in to 1.7.x release.

**Pull request closed without merging**
