### PR TITLE
Remove unmaintained symfony libraries

### PR DESCRIPTION
**Pull request by Shidarr**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     |no
| Fixed issues | 

#### Summary

Drop unmaintained symfony 4.4 libraries

### CODE REVIEW

**Comment by stof** [comment]
This should be submitted in the 3.7.x branch to remove support for Symfony 4.4 in the next minor version rather than in the next patch version IMO.

**Comment by Shidarr** [comment]
Good Idea. Maybe drop support for Versions 5.* also? Because if you update symfony to latest (6.3) Version, you will get some deprecation warnings.

**Comment by stof** [comment]
I don't understand your proposal. Why wanting to drop support for 5.x (where 5.4 is still maintained for 1 year plus an extra year of security fixes) ? you're saying that you get some deprecation warnings when updating to 6.3, but I don't understand how this relates to the support of 5.x

**Comment by Shidarr** [comment]
How to get rid of the deprecation warnings then? 
They are mentioned here also: https://github.com/doctrine/migrations/issues/1329
But the AsCommand Attribute is already added. Deleting the Parameter results in errors in older versions. 
I can also add the Name in configure function and delete parameter. That should work too.

**Comment by derrabus** [comment]
Did you check if this allows us to drop any compat code?

**Comment by Shidarr** [comment]
Ok I just updated the PR to use setName Function instead of $defaultName. This works for old and new symfony/console Versions. Maybe this is better? Then 5.4 is still supported.

**Comment by stof** [comment]
the AsCommand attribute is supported starting in Symfony 5.3. So you don't need to drop support for 5.4.

**Comment by Shidarr** [comment]
Yes with my latest changes 5.4 does not need to be dropped and there is no deprecation warning anymore.

**Comment by derrabus** [comment]
Dropping Symfony 4 was done in #1352 already. The changes you've made to the commands should not be necessary since the `AsCommand` attribute should suppress the deprecation regarding overriding the static properties.

**Comment by derrabus** [comment]
Closing in favor of #1370.

**Pull request closed without merging**
