### PR TITLE
Allow `psr/log` 2 and 3

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | N/A

### CODE REVIEW

**Comment by greg0ire** [comment]
The build is still using `psr/log` 1:

```
composer why-not psr/log 2
symfony/cache  v5.3.3  requires  psr/log (^1.1)
```

**Comment by derrabus** [comment]
> The build is still using `psr/log` 1:

Yes, because your CI tests against stable packages only. You can try this out locally by allowing a dev version of `symfony/cache`.

**Comment by greg0ire** [comment]
Looks like waiting for the next patch version of Symfony would be enough to be sure it actually works: https://github.com/symfony/symfony/pull/42174

Let's do that?

**Comment by derrabus** [comment]
Sure, there's no need to rush anything, I guess.

**Comment by derrabus** [comment]
The PHPUnit job on PHP 8.0 passes with `psr/log` 3.0.0 now.

**Review by goetas — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by goetas** [comment]
@greg0ire since this is marked as improvement, shouldn't target `3.3.x`?

**Comment by derrabus** [comment]
I'm not familiar with the process here, sorry. Shall I relabel it as a bugfix? I don't think that simply widening the version range of a dependency really requires a minor version bump.

**Comment by greg0ire** [comment]
It's more about stability than anything else: huge changes in the tests directory could go to the stable branch. If @derrabus says this change is not a big deal, then I think it's fine to merge it here.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @derrabus!

**Pull request merged**
