### PR TITLE
output backslashes

### LINKED ISSUE #1467: escaped namespaces don't work  in  single quotes
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.8.2

#### Summary
The single quotes should be replaced by double quotes in the text output upon generating a migration diff, so that the pasted command does not fail due to the migration class not being found

#### Current behavior

The instructions for executing the migration uses single quotes:
image
When I copy paste as is, I get class not found.
image
If I change to using quotation marks `"`, it works:
image
 

#### How to reproduce

copy paste the execute down command and see if t runs

#### Expected behavior

It should run without failing

If you like, I can make the changes and send a PR.

### PR DESCRIPTION
**Pull request by delboy1978uk**
fixes #1467

### CODE REVIEW

**Comment by delboy1978uk** [comment]
new output  looks like this 
image

**Comment by greg0ire** [comment]
Please apply @stof 's comment from the issue

**Comment by delboy1978uk** [comment]
@greg0ire I tried that, but it didn't work from a mac, possibly I misunderstood, but he asked me to quote the whole command with `"`? I did that and it forgot the `$PATH` and couldn't even find the command to run. Can someone on a Windows setup check this and suggest any necessary edits?

**Comment by greg0ire** [comment]
> possibly I misunderstood

yes

> but he asked me to quote the whole command with `"`

No he didn't, he asked you "[to use] double quotes in the command", not around it. So, something like `--down "The\\Namespace"`

**Comment by delboy1978uk** [comment]
I'll have a look again tonight, thanks for the feedback

**Comment by delboy1978uk** [comment]
Hi again @greg0ire :-D Apologies that I didn't get the chance to look at this again until now, but I have used quotes now and squashed my commits :-) 
image

**Comment by greg0ire** [comment]
Well there are 2 commits :P

**Comment by delboy1978uk** [comment]
@greg0ire there are now, for some reason I had to apply a CS fix on a line of code that I didn't touch and that hadn't changed in years :-P

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @delboy1978uk !

**Comment by delboy1978uk** [comment]
With pleasure, @greg0ire :-D

**Pull request merged**
