### PR TITLE
Fix: Remove unused imports

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes unused imports

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@localheinz Thanks

**Comment by mikeSimonson** [comment]
@localheinz Did you use a tool to do this ? (which one). Is it possible to put back all the use statement that are used.

I mean that in the sense We have a class A in the namespace Z ( Z\A ) and it use another class B which is also in the namespace Z (Z\B). I would like the class A to import the class B even though it will be find because it's in the same namespace as A.

Also is there a we to change all the \DateTime to use \DateTime ?

Thanks for your time

**Comment by localheinz** [comment]
@mikeSimonson 

I usually use [`fabpot/php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer), for example

```
$ composer global require fabpot/php-cs-fixer:dev-master
```

then, for example, 

```
$ php-cs-fixer fix --verbose --rules=no_unused_imports src
```

I also use PHPStorm and run inspections, it comes up with unused imports, too. Additionally, it provides intentions, for example, to import a class (or simplify a class reference), rather than using a FQCN.

Does that help?

**Comment by mikeSimonson** [comment]
Yes thanks. Those rules don't look like they do what I would like though. :p

**Comment by localheinz** [comment]
@mikeSimonson 

Can submit a PR if you like! Not right now, but towards the weekend, what do you say?

**Comment by stof** [comment]
@mikeSimonson a use statement is about a class in the current namespace. If it is already in the current namespace, there is no point importing it (it is already there)

**Comment by mikeSimonson** [comment]
@stof Even if it's in the current namespace I like the fact that it document the dependencies of a class or you think it's overkill ?

**Pull request merged**
