### PR TITLE
travis: PHP 7.0 nightly added; --dev is by default

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixed spaces to 2, as in other parts of file

### CODE REVIEW

**Comment by stof** [comment]
thanks.

@mikeSimonson what do you think about disallowing failures on HHVM given that the testsuite passes (I think it is too early for PHP 7 though, even though it is passing here)

**Comment by TomasVotruba** [comment]
Thank you

**Comment by mikeSimonson** [comment]
Well if the tests already passes why not ?

**Comment by stof** [comment]
@mikeSimonson what if a new commit in php-src breaks something temporarily ? Do we want our builds to be subject to the instability of the PHP-7 branch ?
However, I'm not against removing it from allow_failures as well. I'm just unsure about the best strategy for now

**Comment by mikeSimonson** [comment]
sorry I meant disallowing failure for hhvm, for php 7 it's a little bit too early I think

**Comment by stof** [comment]
@mikeSimonson done in https://github.com/doctrine/migrations/commit/8a7783409d6e41f8891e2ce997d39cc9145ec167

**Pull request merged**
